language: go
go:
  - 1.11
before_install:
  - sudo service mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql stop
  - docker-compose -p polluter_test up --build -d
  - go get -t -v ./...
  - sleep 3
script:
  - go test -v --race ./...
install: true
env:
  - GO111MODULE=on
