version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./schema/mysql.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - polluter
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root123
    volumes:
      - ./schema/postgres.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - polluter
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - polluter
networks:
    polluter:
        driver: bridge
